### PR TITLE
SC2002 UUOC

### PR DESCRIPTION
**Pull request by Marzal**
Change cat for <
https://github.com/koalaman/shellcheck/wiki/SC2002

### CODE REVIEW

**Comment by er123rin** [comment]
yes

**Comment by Marzal** [comment]
Should I close this PR?

**Review by acslaper — CHANGES_REQUESTED** [review]
Check

**Comment by mboelen** [comment]
Thanks for your pull request. What is the reason to use < instead of cat? Or what is the additional benefit?

**Comment by Marzal** [comment]
Hi, really old PR, I think that 3 years ago there was a series of PR to allign lynis with shellcheck in order to show less warnings and be more compliant with POSIX. I don't remember if this commit had any noticable performance impact (I don't think so). 

TL;NR
One less warning on shellcheck, but I would test again the change since is so old ( this week I don't have a computer around)

**Comment by mboelen** [comment]
Will close this one for now, as the benefit is still unclear to me. If you have the time, feel free to reach out or reopen it. All pull requests are appreciated after all :)

**Pull request closed without merging**
